[server]
addr = "0.0.0.0"
port = 443
redirectToHttps = true

[server.dbbackend]
type 	 = "redis"
username = ""
password = ""
addr     = "127.0.0.1"
port     = 6379
refresh  = 5


[server.services]
    [server.services.python]
        sni = "www.python.org"
        addr = "151.101.240.223:443"

    [server.services.ruby]
        sni = "www.ruby-lang.org"
        addr = "151.101.1.178:443"

    [server.services.localtest]
        sni = "myserver.local"
        addr = "127.0.0.1:8000"
